[config]
skip_core_tasks = true

[tasks.build]
script = "cargo build --release"

[tasks.build-asm]
script_runner = "@shell"
script = """
    if [ ! -d ./asm/target ]; then
        mkdir -p ./asm/target
    fi
    cc -o ./asm/target/main ./asm/main.S
    """

[tasks.run-asm]
script_runner = "@shell"
script = "./asm/target/main"
dependencies = [ "build-asm" ]

[tasks.test]
script = '''
    #!/usr/bin/env bash
    ./debug.sh 0 0
    ./debug.sh 42 42
    ./debug.sh 21 "5+20-4"
    ./debug.sh 41 " 12 + 34 -5 "
    ./debug.sh 47 "5+6*7"
    ./debug.sh 15 "5*(9-6)"
    ./debug.sh 4 "(3+5)/2"
    ./debug.sh 4 "-2+6"
    ./debug.sh 1 "5==4+3 -2"
    ./debug.sh 0 "2>3"
    ./debug.sh 9 """
                    x = 3;
                    y = 4;
                    x + y + 2;
                    """
'''
dependencies = [ "build" ]

[tasks.clean]
script_runner = "@shell"
script = [
    "cargo clean",
    "rm -rf ./tmp"
]